// ------------------------------------------------------------
// Explicit annotation styling
// ------------------------------------------------------------
//
// COLOUR INVARIANT
// ----------------
// Annotation colour is never inferred from an argument position.
// If supplied mathematical or narrative content is coloured, the source
// must say so explicitly by wrapping that content in one of these helpers.
//
// Structural chrome generated by other constructors (theory markers,
// theory titles, section headings, rules, and so on) has its own palette.
// These helpers are for deliberate colouring of user-supplied content.

#import "style.typ": shared-hint-fill, shared-warn-fill
#import "style.typ": shared-accent-fill, shared-contrast-fill, shared-muted-fill
#import "style.typ": shared-tentative-fill, shared-confirmed-fill

// Low-level escape hatch. Prefer a named helper in ordinary source.
#let colour(fill, body) = {
  if fill == none {
    body
  } else {
    text(fill: fill, body)
  }
}

// Everyday rhetorical vocabulary.
#let accent(body) = colour(shared-accent-fill, body)
#let contrast(body) = colour(shared-contrast-fill, body)
#let mute(body) = colour(shared-muted-fill, body)
#let warn(body) = text(
  fill: shared-warn-fill,
  size: 0.95em,
  body,
)

// Calculation reasons sometimes benefit from their own quiet treatment.
// `step` does NOT apply this automatically: write `hint(...)` explicitly.
#let hint(body) = text(
  fill: shared-hint-fill,
  size: 0.95em,
  body,
)

// More specific semantic names are retained for specialised use and
// backwards compatibility. They need not be part of the everyday vocabulary.
#let focus(body) = accent(body)
#let tentative(body) = colour(shared-tentative-fill, body)
#let confirmed(body) = colour(shared-confirmed-fill, body)
#let meta(body) = contrast(body)
