// ------------------------------------------------------------
// Structured theory machinery
// ------------------------------------------------------------
//
// THEORY SEMANTICS
// ----------------
// The row constructors represent different kinds of context extension:
//
//   import-theory(...)  inherit an existing theory context
//   declare(...)        introduce a primitive parameter
//   assume(...)         constrain the current context
//   define(...)         introduce new vocabulary from existing meaning
//   observe(...)        record something derivable from the current context
//   notation(...)       license notation for already meaningful content
//   abbrev(...)         license a contextual abbreviation
//
// Definitions, notation, and abbreviations are deliberately distinct in the
// source even when their rendered rows are visually similar. The distinction
// records what kind of mathematical act is being performed.
//
// STRUCTURAL INVARIANT
// --------------------
// A theory is a genuine two-column grid.
//
//   marker | body
//          | continuation
//          | continuation
//
// The marker occurs ONLY on the first row of a multi-line item.
// Every continuation row contains an explicit blank cell in column 1.
// The column boundary is part of the notation and must not be replaced
// by wrapped or nested content in column 2.
//
// COLOUR INVARIANT
// ----------------
// Theory constructors never infer annotation colour from the position of
// supplied content. If a body or continuation is to be accented, contrasted,
// muted, warned, etc., the caller must wrap that exact content explicitly.
// Structural chrome generated by the theory machinery (markers, headings,
// rules, title) retains the shared structural palette.

#import "style.typ": shared-rule-fill, shared-primary-fill, shared-secondary-fill, shared-marker-fill

#let qed = [$square.filled.small$]
#let normal(x) = math.class("normal", x)

// Primitive: exactly one two-cell theory row.
#let theory-row(mark, body) = (
  [
    // Keep marker and body on the same vertical footing. The grid aligns
    // cells by their boxes, so asymmetric padding makes markers such as
    // `1.` appear slightly high beside mathematical content.
    #pad(y: 0.12em)[
      #text(fill: shared-marker-fill)[#mark]
    ]
  ],
  [
    #pad(y: 0.12em)[#body]
  ],
)

// Build explicit blank-marker continuation rows.
// `body` values are already Typst content (for mathematical lines,
// normally `$...$`). Do not wrap them in another math environment.
#let _continuation-rows(..bodies) = {
  let rows = ()
  for body in bodies.pos() {
    rows += theory-row([], body)
  }
  rows
}

// Generic marked item. The first row has the marker; all later rows have
// an explicit blank first cell and therefore remain in column 2.
#let theory-line(mark, body, ..continuations) = {
  let rows = theory-row(mark, body)
  rows += _continuation-rows(..continuations)
  rows
}

// Prose uses exactly the same row discipline. The separate name is semantic:
// it says that the bodies are narrative content rather than formulae.
#let theory-text-row(mark, body, ..continuations) = theory-line(
  mark,
  body,
  ..continuations,
)

#let section(title) = theory-row(
  [],
  [
    #text(
      fill: shared-secondary-fill,
      size: 0.9em,
      weight: "semibold",
    )[#title]
  ],
)

#let empty-theory-row = theory-row([], [])

// Quiet punctuation within a theory. This is a genuine two-cell theory row:
// the marker cell remains blank and the rule occupies only the body column.
// Keeping it inside the normal row structure preserves pagination and the
// semantic marker/body boundary.
#let theory-separator(
  length: 100%,
  stroke: 0.4pt + shared-rule-fill,
) = theory-row(
  [],
  [#line(length: length, stroke: stroke)],
)

// Semantic constructors.
// Mathematical bodies are passed as already-formed content, e.g. `$R ⊆ S$`.
#let declare(name, typ, ..continuations) = {
  let rows = theory-row("+", [$#name in typ$])
  rows += _continuation-rows(..continuations)
  rows
}

#let imports(body, ..continuations) = theory-line(
  $convolve$,
  body,
  ..continuations,
)

#let sub(lhs, rhs) = $lhs colon.eq rhs$
#let subs(..items) = items.pos().join($, $)
#let using(name, subst) = $#name [#subst]$

#let import-theory(name, subst: none) = {
  if subst == none {
    imports(name)
  } else {
    imports(using(name, subst))
  }
}

#let assume(label, body, ..continuations) = theory-line(
  label,
  body,
  ..continuations,
)

#let observe(label, body, ..continuations) = theory-line(
  label,
  body,
  ..continuations,
)

// Definitions use `+` by default, but may carry an explicit reference label.
// `label` is named so existing calls such as `define($x := y$)` remain valid.
#let define(body, label: "+", ..continuations) = theory-line(
  label,
  body,
  ..continuations,
)

// Notation and contextual abbreviations are first-class theory acts.
// As with `define`, the caller supplies the complete statement so that the
// library does not choose a definitional symbol on the mathematician's behalf.
// `+` remains the default marker because both constructs introduce usable
// vocabulary into the current context without adding a new assumption.
#let notation(body, label: "+", ..continuations) = theory-line(
  label,
  body,
  ..continuations,
)

#let abbrev(body, label: "+", ..continuations) = theory-line(
  label,
  body,
  ..continuations,
)

// Narrative material inside a theory. It deliberately has no marker.
#let remark(body, ..continuations) = theory-text-row(
  [],
  body,
  ..continuations,
)

// Row constructors are supplied directly as variadic arguments.
#let theory(
  title,
  width: auto,
  min-width: 45%,
  inset: 9pt,
  stroke: shared-rule-fill,
  ..rows,
) = block(
  // A block, unlike a box, can continue across page boundaries.
  // Keep width:auto so the framed theory remains content-sized rather than
  // expanding to the full text width. Explicit zero spacing preserves the
  // document rhythm of the former box-based implementation.
  breakable: true,
  stroke: stroke,
  inset: inset,
  width: width,
  above: 0pt,
  below: 0pt,
)[
  #grid(
    // The marker track grows to the widest marker actually used.
    // The body track remains independently content-sized.
    columns: (auto, auto),
    column-gutter: 0.6em,
    row-gutter: 0.75em,
    align: left,

    [#text(fill: shared-marker-fill)[§]],
    [
      // The vertical stack makes the cell as wide as the larger of:
      //   * the title itself, and
      //   * the invisible minimum-width strut.
      //
      // This gives the body column a genuine minimum without adding the
      // title width to that minimum and without constraining the title
      // to the minimum width.
      #stack(
        dir: ttb,
        spacing: 0pt,
        [#text(fill: shared-primary-fill, weight: "bold")[#title]],
        box(width: min-width, height: 0pt)[],
      )
    ],

    ..rows.pos().flatten(),

    [#text(fill: shared-marker-fill)[#qed]],
    []
  )
]

// Explicit naked presentation: no frame and no centring.
#let unboxed-theory(
  title,
  width: auto,
  min-width: 45%,
  ..rows,
) = theory(
  title,
  width: width,
  min-width: min-width,
  inset: 0pt,
  stroke: none,
  ..rows,
)

#let centred-theory(
  title,
  width: auto,
  min-width: 45%,
  inset: 9pt,
  stroke: shared-rule-fill,
  ..rows,
) = align(center)[
  #theory(
    title,
    width: width,
    min-width: min-width,
    inset: inset,
    stroke: stroke,
    ..rows,
  )
]
